spring:
  application:
    name: daycare
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/daycare}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:rootpassword}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false

jwt:
  issuer: daycare-api
  # TTL = Time To Live = durée de vie du token avant expiration
  access-token-ttl-seconds: 900     # 15 minutes
  refresh-token-ttl-seconds: 604800 # 7 jours (7 * 24h)
  # Clé symétrique HMAC (HS256) : string brute, min. 32 caractères (256 bits)
  secret: ${JWT_SECRET:change-me-in-prod-with-a-32-bytes-secret}
