/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DaycareDetailResponse { 
    id?: string;
    osmId?: number;
    name?: string;
    latitude?: number;
    longitude?: number;
    houseNumber?: string;
    street?: string;
    postcode?: string;
    city?: string;
    phone?: string;
    operator?: string;
    siret?: string;
    note?: string;
    source?: string;
    status?: DaycareDetailResponse.StatusEnum;
}
export namespace DaycareDetailResponse {
    export const StatusEnum = {
        AContacter: 'A_CONTACTER',
        Contacte: 'CONTACTE',
        Entretien: 'ENTRETIEN',
        Accepte: 'ACCEPTE',
        Refuse: 'REFUSE'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


