/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DaycareDetailResponse { 
    id?: string;
    externalId?: string;
    type?: DaycareDetailResponse.TypeEnum;
    name?: string;
    latitude?: number;
    longitude?: number;
    houseNumber?: string;
    street?: string;
    postcode?: string;
    city?: string;
    department?: string;
    phone?: string;
    email?: string;
    websiteUrl?: string;
    operator?: string;
    siret?: string;
    note?: string;
    source?: string;
    status?: DaycareDetailResponse.StatusEnum;
}
export namespace DaycareDetailResponse {
    export const TypeEnum = {
        Eaje: 'EAJE',
        Alsh: 'ALSH',
        Rpe: 'RPE',
        Laep: 'LAEP',
        Mecs: 'MECS',
        CentreMaternel: 'CENTRE_MATERNEL',
        VillageEnfants: 'VILLAGE_ENFANTS',
        Pmi: 'PMI',
        CentreHospitalier: 'CENTRE_HOSPITALIER',
        Autre: 'AUTRE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const StatusEnum = {
        AContacter: 'A_CONTACTER',
        Contacte: 'CONTACTE',
        Entretien: 'ENTRETIEN',
        Accepte: 'ACCEPTE',
        Refuse: 'REFUSE'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


